scoreboard:
  display-name: '&f» &e&lMineage&6&lPVP &f«'
  lines:
    - '&7&m------------------------'
    - '&dBalance: &e$%vault_eco_balance_fixed%'
    - '&dFaction: &e{faction_name}'
    - '&dTPS: &e{tps}'
    - '&dDiscord: &ediscord.gg/eMhFHSp'
    - '&7&m-----------&7&m-------------'
vouchers:
  protein:
    commands:
      - 'broadcast {player} has won a protein tag!'
    item:
      name: '&cProtein'
      material: 'NAME_TAG'
      lore:
        - '&eRight click to redeem the Protein tag'
  fix-all:
    commands:
      - 'broadcast &a{player} &ehas redeemed /fixall!'
      - 'perm user {player} group add perk-fixall'
    item:
      name: '&a/FixAll'
      material: 'NAME_TAG'
      lore:
        - '&eRight click to redeem the Fix all command'
  fix-hand:
    commands:
      - 'broadcast &a{player} &ehas redeemed /fixhand!'
      - 'perm user {player} group add perk-fixhand'
    item:
      name: '&a/FixHand'
      material: 'NAME_TAG'
      lore:
        - '&eRight click to redeem the Fix Hand command'
  villager:
    commands:
      - 'broadcast &a{player} &ehas redeemed Villager Rank!'
    item:
      name: '&eVillager Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Villager Rank'
        - '&cThese will not replace your current rank if you are higher than Villager!'
  knight:
    commands:
      - 'broadcast &a{player} &ehas redeemed Knight Rank!'
    item:
      name: '&6Knight Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Knight Rank'
        - '&cThese will not replace your current rank if you are higher than Knight!'
  king:
    commands:
      - 'broadcast &a{player} &ehas redeemed King Rank!'
    item:
      name: '&9King Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem King Rank'
        - '&cThese will not replace your current rank if you are higher than King!'
  god:
    commands:
      - 'broadcast &a{player} &ehas redeemed God Rank!'
    item:
      name: '&bGod Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem God Rank'
        - '&cThese will not replace your current rank if you are higher than God!'
  overseer:
    commands:
      - 'broadcast &a{player} &ehas redeemed Overseer Rank!'
    item:
      name: '&dOverseer Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Overseer Rank'
        - '&cThese will not replace your current rank if you are higher than Overseer!'
  zeus:
    commands:
      - 'broadcast &a{player} &ehas redeemed Zeus Rank!'
    item:
      name: '&cZeus'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Zeus Rank'
        - '&cThese will not replace your current rank if you are higher than Zeus!'
  endergod:
    commands:
      - 'broadcast &a{player} &ehas redeemed Endergod Rank!'
    item:
      name: '&5ndergod Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Endergod Rank'
        - '&cThese will not replace your current rank if you are higher than Endergod!'
  witherking:
    commands:
      - 'broadcast &a{player} &ehas redeemed Witherking Rank!'
    item:
      name: '&3&lWither&7&lking &3Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Witherking Rank'
        - '&cThese will not replace your current rank if you are higher than Witherking!'
  netherlord:
    commands:
      - 'broadcast &a{player} &ehas redeemed Netherlord Rank!'
    item:
      name: '&4&lNether&6&llord &4Rank'
      material: 'PAPER'
      lore:
        - '&eRight click to redeem Netherlord Rank'
        - '&cThese will not replace your current rank if you are higher than Netherlord!'
faction-collectors:
  collector-item:
    name: '&bFaction Collector'
    enchanted: true
    lore:
      - ''
      - '&dPlace this down in your claims to start collecting mobs.'
      - ''
  sellwand-item:
    name: '&eSell Wand'
    material: 'DIAMOND_HOE'
    enchanted: true
    lore:
      - ''
      - '&dRight click a collector to sell all of the mobs.'
      - ''
  tntwand-item:
    name: '&cTNT Wand'
    material: 'GOLD_HOE'
    enchanted: false
    lore:
      - ''
      - '&dRight click a collector to deposit all of the tnt.'
      - ''
  harvesterhoe-item:
    name: '&bHarvester Hoe'
    material: 'DIAMOND_HOE'
    enchanted: true
    lore:
      - ''
      - '&dBreak sugar cane to and have a chance to receieve double the amount!'
      - ''
  gui:
    items:
      info:
        name: '&5INFO'
        material: 'BOOK'
        lore:
          - '&fThis is a faction collector.'
      locked:
        name: '&e&l(!) &f{mob} &e&l(!)'
        lore:
          - '&cThis collection type is locked, upgrade your collector to unlock it.'
      collection-type-format:
        name: '&e&l(!) &f{mob} &e&l(!)'
        lore:
          - '&eYou have &c{amount} &eavailable to sell.'
      upgrade:
        name: '&dUpgrade'
        material: 'DIAMOND_BLOCK'
        lore:
          - '&eClick to upgrade to level {level} for ${price}'
      max-upgrade:
        name: '&dUpgrade'
        material: 'BEDROCK'
        lore:
          - '&cMaximum upgrade reached!'
sell-values:
  chicken: 3.0
  pig-zombie: 17.0
  enderman: 14.0
  cow: 8.0
  pig: 5.0
  villager: 20.0
  iron-golem: 25.0
  witch: 20.0
  cactus: 2.0
  sugar-cane: 4.0
upgrade-prices:
  1: 100000.0
  2: 250000.0
  3: 500000.0